name=ESPAsyncHTTPClient
version=1.0.0
author=Alex Bratchik
maintainer=Alex Bratchik <abratchik@gmail.com>
sentence=Async HTTP Client for ESP8266 and ESP32
paragraph=A simple lightweight HTTP client based on ESPAsyncTCP library
category=Communication
url=https://github.com/abratchik/ESPAsyncHTTPClient
architectures=espressif8266, espressif32